# Generated by Django 4.1.3 on 2022-12-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id_maquina', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=500)),
            ],
        ),
    ]
