# Generated by Django 3.2.16 on 2022-12-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dssProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='capacidad',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='maquina',
            name='tarea',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
