# Generated by Django 3.2.16 on 2022-12-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dssProject', '0002_auto_20221208_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='tarea',
            field=models.CharField(max_length=500),
        ),
    ]
