# Generated by Django 3.2.16 on 2022-12-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dssProject', '0004_mantencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id_schedule', models.AutoField(primary_key=True, serialize=False)),
                ('tarea', models.CharField(max_length=500)),
                ('grupo', models.IntegerField(blank=True, default=0)),
                ('maquina', models.CharField(max_length=500)),
                ('horario', models.CharField(max_length=500)),
                ('carga', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
