# Generated by Django 3.2.16 on 2022-12-29 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dssProject', '0005_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='dia',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id_schedule',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
