# Generated by Django 3.2.16 on 2022-12-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dssProject', '0007_auto_20221229_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='id_schedule',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
