# Generated by Django 3.2.16 on 2023-01-03 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dssProject', '0008_alter_schedule_id_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantencion',
            old_name='fecha',
            new_name='dia',
        ),
        migrations.RenameField(
            model_name='mantencion',
            old_name='semana',
            new_name='final',
        ),
        migrations.RemoveField(
            model_name='mantencion',
            name='id_maquina',
        ),
        migrations.AddField(
            model_name='mantencion',
            name='inicio',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantencion',
            name='tipo',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
